name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U app"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      APP_ENV: test
      DATABASE_URL: postgresql://app:app@127.0.0.1:5432/app?serverVersion=16&charset=utf8

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: ctype, iconv, intl, mbstring, pgsql, pdo_pgsql
          tools: composer:v2

      - name: Installer les dépendances
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Créer la base de test
        run: php bin/console doctrine:database:create --env=test

      - name: Jouer les migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Charger les fixtures
        run: php bin/console doctrine:fixtures:load --no-interaction --env=test

      - name: Lancer les tests
        run: php bin/phpunit